SELECT SUM(CITY.POPULATION)
FROM CITY, COUNTRY
WHERE CITY.COUNTRYCODE = COUNTRY.CODE
AND COUNTRY.CONTINENT = "Asia";

SELECT SUM(a.POPULATION)
FROM CITY AS a, COUNTRY AS b
WHERE a.COUNTRYCODE = b.CODE 
AND b.CONTINENT = "Asia";

SELECT SUM(CITY.POPULATION)
FROM CITY
JOIN COUNTRY
ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE COUNTRY.CONTINENT = "Asia";
